name: Filter Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - LICENSE
  schedule:
    # At 09:00am each Monday
    - cron: "0 9 * * 1"
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TARGET_FILE: test.md
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run pandoc
        uses: docker://pandoc/core:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --lua-filter curly-switch.lua
            -t markdown
            -o ${TARGET_FILE}
            test/info.md
      - name: Test
        run: ls -al
      - name: Check variables replacement 
        run: >-
          grep -q "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" ${TARGET_FILE} && \
          grep -q "lua" ${TARGET_FILE} && \
          grep -q "Apache License, 2.0" ${TARGET_FILE} && \
          grep -q "Claudio Di Vita" ${TARGET_FILE}